# Data Mining and Analysis Lab Work: Implementation of Classification on Divorce Dataset in Python (LAB 7)
## Dated: May 31, 2021
### Submitted To: Dr. Varun Gupta
### Submitted By: Anshul Gupta (CO18311)
#### Software Used: IBM Watson Studio

### Step 1: Data Preprocessing

#### Importing Required Libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#### Importing the Dataset

In [2]:
import os, types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share the notebook.

if os.environ.get('RUNTIME_ENV_LOCATION_TYPE') == 'external':
    endpoint_0a540e30cc1440b39b57345b3721ab45 = 'https://s3-api.us-geo.objectstorage.softlayer.net'
else:
    endpoint_0a540e30cc1440b39b57345b3721ab45 = 'https://s3-api.us-geo.objectstorage.service.networklayer.com'

client_0a540e30cc1440b39b57345b3721ab45 = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='Y-0cVIXL068746-WzuC3_ASyZ5pfIwZNcG7UpjNtaYnx',
    ibm_auth_endpoint="https://iam.cloud.ibm.com/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url=endpoint_0a540e30cc1440b39b57345b3721ab45)

body = client_0a540e30cc1440b39b57345b3721ab45.get_object(Bucket='dataminingandanalysislab-donotdelete-pr-fpuetwfuzbmdpt',Key='divorce.csv')['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

dataset = pd.read_csv(body)
dataset


Atr1  Atr2  Atr3  Atr4  Atr5  Atr6  Atr7  Atr8  Atr9  Atr10  ...  Atr46  \
0       2     2     4     1     0     0     0     0     0      0  ...      2   
1       4     4     4     4     4     0     0     4     4      4  ...      2   
2       2     2     2     2     1     3     2     1     1      2  ...      3   
3       3     2     3     2     3     3     3     3     3      3  ...      2   
4       2     2     1     1     1     1     0     0     0      0  ...      2   
..    ...   ...   ...   ...   ...   ...   ...   ...   ...    ...  ...    ...   
165     0     0     0     0     0     0     0     0     0      0  ...      1   
166     0     0     0     0     0     0     0     0     0      0  ...      4   
167     1     1     0     0     0     0     0     0     0      1  ...      3   
168     0     0     0     0     0     0     0     0     0      0  ...      3   
169     0     0     0     0     0     0     0     1     0      0  ...      3   

     Atr47  Atr48  Atr49  Atr50  Atr51  Atr52  Atr53  Atr54  Class  
0        1      3      3      3      2      3      2      1      1  
1        2      3      4      4      4      4      2      2      1  
2        2      3      1      1      1      2      2      2      1  
3        2      3      3      3      3      2      2      2      1  
4        1      2      3      2      2      2      1      0      1  
..     ...    ...    ...    ...    ...    ...    ...    ...    ...  
165      0      4      1      1      4      2      2      2      0  
166      1      2      2      2      2      3      2      2      0  
167      0      2      0      1      1      3      0      0      0  
168      3      2      2      3      2      4      3      1      0  
169      4      4      0      1      3      3      3      1      0  

[170 rows x 55 columns]

### Attribute Information:

1. If one of us apologizes when our discussion deteriorates, the discussion ends.
2. I know we can ignore our differences, even if things get hard sometimes.
3. When we need it, we can take our discussions with my spouse from the beginning and correct it.
4. When I discuss with my spouse, to contact him will eventually work.
5. The time I spent with my wife is special for us.
6. We don't have time at home as partners.
7. We are like two strangers who share the same environment at home rather than family.
8. I enjoy our holidays with my wife.
9. I enjoy traveling with my wife.
10. Most of our goals are common to my spouse.
11. I think that one day in the future, when I look back, I see that my spouse and I have been in harmony with each other.
12. My spouse and I have similar values in terms of personal freedom.
13. My spouse and I have similar sense of entertainment.
14. Most of our goals for people (children, friends, etc.) are the same.
15. Our dreams with my spouse are similar and harmonious.
16. We're compatible with my spouse about what love should be.
17. We share the same views about being happy in our life with my spouse
18. My spouse and I have similar ideas about how marriage should be
19. My spouse and I have similar ideas about how roles should be in marriage
20. My spouse and I have similar values in trust.
21. I know exactly what my wife likes.
22. I know how my spouse wants to be taken care of when she/he sick.
23. I know my spouse's favorite food.
24. I can tell you what kind of stress my spouse is facing in her/his life.
25. I have knowledge of my spouse's inner world.
26. I know my spouse's basic anxieties.
27. I know what my spouse's current sources of stress are.
28. I know my spouse's hopes and wishes.
29. I know my spouse very well.
30. I know my spouse's friends and their social relationships.
31. I feel aggressive when I argue with my spouse.
32. When discussing with my spouse, I usually use expressions such as ‘you always’ or ‘you never’ .
33. I can use negative statements about my spouse's personality during our discussions.
34. I can use offensive expressions during our discussions.
35. I can insult my spouse during our discussions.
36. I can be humiliating when we discussions.
37. My discussion with my spouse is not calm.
38. I hate my spouse's way of open a subject.
39. Our discussions often occur suddenly.
40. We're just starting a discussion before I know what's going on.
41. When I talk to my spouse about something, my calm suddenly breaks.
42. When I argue with my spouse, ı only go out and I don't say a word.
43. I mostly stay silent to calm the environment a little bit.
44. Sometimes I think it's good for me to leave home for a while.
45. I'd rather stay silent than discuss with my spouse.
46. Even if I'm right in the discussion, I stay silent to hurt my spouse.
47. When I discuss with my spouse, I stay silent because I am afraid of not being able to control my anger.
48. I feel right in our discussions.
49. I have nothing to do with what I've been accused of.
50. I'm not actually the one who's guilty about what I'm accused of.
51. I'm not the one who's wrong about problems at home.
52. I wouldn't hesitate to tell my spouse about her/his inadequacy.
53. When I discuss, I remind my spouse of her/his inadequacy.
54. I'm not afraid to tell my spouse about her/his incompetence.

In [3]:
X=dataset.drop('Class', axis=1)
y=dataset['Class']

In [4]:
X

Atr1  Atr2  Atr3  Atr4  Atr5  Atr6  Atr7  Atr8  Atr9  Atr10  ...  Atr45  \
0       2     2     4     1     0     0     0     0     0      0  ...      3   
1       4     4     4     4     4     0     0     4     4      4  ...      2   
2       2     2     2     2     1     3     2     1     1      2  ...      2   
3       3     2     3     2     3     3     3     3     3      3  ...      3   
4       2     2     1     1     1     1     0     0     0      0  ...      2   
..    ...   ...   ...   ...   ...   ...   ...   ...   ...    ...  ...    ...   
165     0     0     0     0     0     0     0     0     0      0  ...      0   
166     0     0     0     0     0     0     0     0     0      0  ...      3   
167     1     1     0     0     0     0     0     0     0      1  ...      2   
168     0     0     0     0     0     0     0     0     0      0  ...      4   
169     0     0     0     0     0     0     0     1     0      0  ...      1   

     Atr46  Atr47  Atr48  Atr49  Atr50  Atr51  Atr52  Atr53  Atr54  
0        2      1      3      3      3      2      3      2      1  
1        2      2      3      4      4      4      4      2      2  
2        3      2      3      1      1      1      2      2      2  
3        2      2      3      3      3      3      2      2      2  
4        2      1      2      3      2      2      2      1      0  
..     ...    ...    ...    ...    ...    ...    ...    ...    ...  
165      1      0      4      1      1      4      2      2      2  
166      4      1      2      2      2      2      3      2      2  
167      3      0      2      0      1      1      3      0      0  
168      3      3      2      2      3      2      4      3      1  
169      3      4      4      0      1      3      3      3      1  

[170 rows x 54 columns]

In [5]:
y

0      1
1      1
2      1
3      1
4      1
      ..
165    0
166    0
167    0
168    0
169    0
Name: Class, Length: 170, dtype: int64

#### Splitting the dataset into the Training set and Test set

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.30, shuffle=True, random_state = 0)

In [7]:
f'Shapes: X_train:{X_train.shape},y_train:{y_train.shape}, X_test:{X_test.shape}, y_test:{y_test.shape}'

'Shapes: X_train:(119, 54),y_train:(119,), X_test:(51, 54), y_test:(51,)'

#### Feature Scaling

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

### Step 2: Training of the model

#### Fitting Simple Logistic Regression to the dataset

In [9]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

#### Predicting the test set results

In [10]:
y_pred = classifier.predict(X_test)

### Step 3: Confusion Matrix

In [11]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[27  0]
 [ 2 22]]


In [12]:
from sklearn.metrics import classification_report
cr = classification_report(y_test, y_pred)
print(cr)

              precision    recall  f1-score   support

           0       0.93      1.00      0.96        27
           1       1.00      0.92      0.96        24

    accuracy                           0.96        51
   macro avg       0.97      0.96      0.96        51
weighted avg       0.96      0.96      0.96        51



## Implementing Simple KNN

In [13]:
from sklearn.neighbors import KNeighborsClassifier
classifier1 = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier1.fit(X_train, y_train)

KNeighborsClassifier()

In [14]:
#Prediction
y_pred1 = classifier1.predict(X_test)

In [15]:
#Confusion Matrix
from sklearn.metrics import confusion_matrix
cm1 = confusion_matrix(y_test, y_pred1)
print(cm1)

[[27  0]
 [ 2 22]]


In [16]:
cr_knn = classification_report(y_test, y_pred1)
print(cr_knn)

              precision    recall  f1-score   support

           0       0.93      1.00      0.96        27
           1       1.00      0.92      0.96        24

    accuracy                           0.96        51
   macro avg       0.97      0.96      0.96        51
weighted avg       0.96      0.96      0.96        51



## Implementing SVM

In [17]:
from sklearn.svm import SVC
classifier2=SVC(kernel='linear', random_state=0 )
classifier2.fit(X_train, y_train)

SVC(kernel='linear', random_state=0)

In [18]:
#Prediction
y_pred2 = classifier2.predict(X_test)

In [19]:
#Confusion Matrix
from sklearn.metrics import confusion_matrix
cm_svc = confusion_matrix(y_test, y_pred2)
print(cm_svc)

[[27  0]
 [ 2 22]]


In [20]:
cr_svc = classification_report(y_test, y_pred1)
print(cr_svc)

              precision    recall  f1-score   support

           0       0.93      1.00      0.96        27
           1       1.00      0.92      0.96        24

    accuracy                           0.96        51
   macro avg       0.97      0.96      0.96        51
weighted avg       0.96      0.96      0.96        51



## Implementing Kernel-SVM

In [21]:
from sklearn.svm import SVC
classifier3 = SVC(kernel = 'rbf', random_state = 0)
classifier3.fit(X_train, y_train)

SVC(random_state=0)

In [22]:
#Prediction
y_pred3 = classifier3.predict(X_test)

In [23]:
#Confusion Matrix
from sklearn.metrics import confusion_matrix
cm_ksvm = confusion_matrix(y_test, y_pred3)
print(cm_ksvm)

[[27  0]
 [ 2 22]]


In [24]:
cr_ksvm = classification_report(y_test, y_pred3)
print(cr_ksvm)

              precision    recall  f1-score   support

           0       0.93      1.00      0.96        27
           1       1.00      0.92      0.96        24

    accuracy                           0.96        51
   macro avg       0.97      0.96      0.96        51
weighted avg       0.96      0.96      0.96        51



## Implementing Decision Tree

In [25]:
from sklearn.tree import DecisionTreeClassifier
classifier4 = DecisionTreeClassifier(criterion= 'entropy',max_depth = 10, splitter='best', random_state=2020)
classifier4.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=10, random_state=2020)

In [26]:
#Prediction
y_pred_4 = classifier4.predict(X_test)

In [27]:
y_pred_4

array([0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 0])

In [28]:
#Confusion Matrix
cm_dt = confusion_matrix(y_test, y_pred_4)
cm_dt

array([[24,  3],
       [ 1, 23]])

In [29]:
cr_dt = classification_report(y_test, y_pred_4, target_names = ['0','1'])
print(cr_dt)

              precision    recall  f1-score   support

           0       0.96      0.89      0.92        27
           1       0.88      0.96      0.92        24

    accuracy                           0.92        51
   macro avg       0.92      0.92      0.92        51
weighted avg       0.92      0.92      0.92        51



## Implementing Random Forest

In [30]:
from sklearn.ensemble import RandomForestClassifier
classifier5 = RandomForestClassifier(max_depth=2, random_state=0)
classifier5.fit(X_train, y_train)

RandomForestClassifier(max_depth=2, random_state=0)

In [31]:
#Prediction
y_pred_5 = classifier5.predict(X_test)

In [32]:
#Confusion Matrix
cm_rf = confusion_matrix(y_test, y_pred_5)
print(cm_rf)

[[27  0]
 [ 2 22]]


In [33]:
cr_rf = classification_report(y_test, y_pred_5, target_names = ['0','1'])
print(cr_rf)

              precision    recall  f1-score   support

           0       0.93      1.00      0.96        27
           1       1.00      0.92      0.96        24

    accuracy                           0.96        51
   macro avg       0.97      0.96      0.96        51
weighted avg       0.96      0.96      0.96        51

